insert into users (name, username, password, email, avatar_url, bio, verified) values ('André', 'andre', '$2a$12$w2gGJ4mqQR9a57qzmoEvp.E7ufyQsxDy3dppP0x1HqvbGfUr1mK.y', 'andre@parrot.io', null, 'I am the creator of this application.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Eileen', 'ealsobrook1', '$2a$04$LxOvSC2y.cmmZnU.5V8Je.Ka1RBCpzi4thsOEbDKqkp4L.QkMHn0u', 'ekelner1@nih.gov', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Thedric', 'tbelcher2', '$2a$04$KXFc1Vo3kmOYr.kwmBn/5uFAiRj6B8pUOc3VImtwLWYvYB4GiO61q', 'tmurty2@altervista.org', 'https://robohash.org/quiainventorecorrupti.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Catlaina', 'cturle3', '$2a$04$q97GHDFAFYvKQWOjc7bmzOErUhEyXiQvP58ygbWSngOOOV66wKca.', 'ctopaz3@skyrock.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Jessy', 'jfairbank4', '$2a$04$uSckN2plPBcdpgTO9G8y.eQFW3mIBuUctOa77HekWyzh9koSXymWG', 'jfranzetti4@taobao.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Clint', 'cdobbin5', '$2a$04$FUegh7w3tOpEl3A3rxCxo.uK.A9OUNOoXDp62gY9Y8wuBC0zIQHjO', 'ctetford5@omniture.com', 'https://robohash.org/deseruntdistinctioquia.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Ximenez', 'xbeeble6', '$2a$04$Xg/JAhHb/QYDtHWWdUd.aeOlpYTVrt/MDEolbH35DR6FvRsA/JXs2', 'xhevey6@google.pl', 'https://robohash.org/estautemnemo.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Jock', 'jmcgilben7', '$2a$04$vjkBOhukwj1y3ZZiy.EfnO2wd6HOQgzKqhoJqw89usRYWNCjaTBXi', 'jteml7@networksolutions.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Dorthy', 'dplacidi8', '$2a$04$Rc68jtDp6yTq1kfhWSb53e0mJemjM3njd8gVuOilQmO3KyklQ5mrm', 'dlowing8@bloglines.com', 'https://robohash.org/assumendanostrumsunt.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Forbes', 'fboydon9', '$2a$04$e3f/yLAr4/qet.HaMzJN3ulR6j.Wi27bCEB1bt/mLg9T.RtXOVrX6', 'fdonati9@slate.com', 'https://robohash.org/sedevenietnemo.jpg?size=500x500&set=set1', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Darcy', 'dcoronasa', '$2a$04$/2EEmhhXOicqZtsBIPE1z.Qp1X5VPFicMiR89RyJUduA6g2n8RL8C', 'dconena@nytimes.com', 'https://robohash.org/voluptatemsedquis.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Sargent', 'sstensonb', '$2a$04$4Wlv.T.HEfc3EvwHFlQ7ketNzCtRbaakWv0NFqxnXq7sZ9evl0RC2', 'srennieb@photobucket.com', 'https://robohash.org/autrecusandaetenetur.jpg?size=500x500&set=set1', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Rhea', 'rhaneyc', '$2a$04$rlh9yyz8/EjJyzK3l16.KuPocEmxlVshlVexf6/DN0S9Kz/iu3ZR6', 'rokenfoldc@com.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Sonny', 'sdulyd', '$2a$04$WAMfeOOFl9HKgz7dt.oVdOWi00p.a5n4FgjGGWTnvnODaaIAvtv.O', 'shalleyd@umn.edu', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Constantino', 'cbeveridgee', '$2a$04$aYFa24GjbhZNk4mCX4IZoOYnSrl3G4m4o2A.KmezzcoxdNOgFTEJC', 'ccreeke@spotify.com', 'https://robohash.org/autquidemincidunt.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Arnold', 'aplaskettf', '$2a$04$4Qg6TAu0WbG2tLeFKdE.2uoAugMYR6oxvCjQP.Aqc87.o59ZX2Sim', 'abartrumf@cnbc.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Moises', 'mfigguresg', '$2a$04$JHCTyko84yUHLYyHn6HuheM8OqkABg7fStYmiWL9RBdDfGIHsnywm', 'mdomleog@sciencedirect.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Edy', 'esemensh', '$2a$04$y5zvaya33Fw4aLP.mc.JtuIUyMyrjTRLiFbeUA9oLNqVLKsb8osRO', 'edebellh@godaddy.com', 'https://robohash.org/quoperspiciatisnon.jpg?size=500x500&set=set1', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Bree', 'bboarderi', '$2a$04$4lx.bNr4hC8CUUF1HG.bI.3vqPYwCpkH7WDIenIXhvKEQcEsqfHhe', 'bchapmani@bluehost.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Melicent', 'mtimsonj', '$2a$04$xBkMtvDCJBgikKu8ZE0zTOXVFLqwc/a7mg.6Ov.eStF/zmcPteC/6', 'mworldj@examiner.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Domenic', 'dwaycottk', '$2a$04$.0fQF86jN1ilSrqh8NXxUuHTmQN70XxOJbLJH7nFWiQ0bkS8QM0C6', 'ddefrainek@zdnet.com', 'https://robohash.org/nonveniamet.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Ilsa', 'igrutl', '$2a$04$nmAmMIf9MzkkXhZERgDymeEcENYh1zR7KKCRWaofY98z0kSmuOfAu', 'icolesl@columbia.edu', null, 'In congue. Etiam justo. Etiam pretium iaculis justo.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Kenn', 'krainfordm', '$2a$04$OEvOwwdQQZDJvyS0rIq3yOFH4Ada8VXJ5xgpJYmigyFj8V/zECVaG', 'kmoratm@ifeng.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Andi', 'amaberleyn', '$2a$04$jW5TYas4IgybDnePQxT1vO/LLrPcXsNp3iqEpuxOBqxnmLszxiFbm', 'aromanellin@yellowpages.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Susi', 'sfrekeo', '$2a$04$8PfzJ4mTKOQ0dmcmjYj5KOfG3nJPozZ50ObbhMr3.R8zgaJG.XIQe', 'sfouliso@guardian.co.uk', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Antonietta', 'aedgsonp', '$2a$04$Av4wxLq3uy12oYDTQUpKleqSSCCq9cNAf59F6OrrJoJ5168z8hklC', 'aorsayp@pen.io', 'https://robohash.org/voluptatemdoloremab.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Inna', 'ifargeq', '$2a$04$LY5jQadPJcX2aaBRcKEii.iH0nDEdvv364pKc.uyhQ73QnPvZp4Mm', 'idarbyq@abc.net.au', 'https://robohash.org/illoidlibero.jpg?size=500x500&set=set1', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Gard', 'gglyssanner', '$2a$04$38VKUQErv/RRQZXHPVyg.eyuR8X.Z1t5wwQ2ZMnGvX.QAdmrWlUyK', 'gbewlyr@oaic.gov.au', 'https://robohash.org/aspernaturidnulla.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Wilhelm', 'wgermans', '$2a$04$ynnMecwV1OqSCOxElOL3pOtNsxql0BWl8.dl2ioIQaqBWUlMHUwmW', 'wdunsmuirs@soup.io', 'https://robohash.org/quieumoccaecati.jpg?size=500x500&set=set1', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Goldina', 'gspencert', '$2a$04$jWKNjtEPiYNFHvlS5P7ATOJAq1ckgMoXBuJobWiWSeMe7K9/Xr0uq', 'gkobust@histats.com', 'https://robohash.org/velitutlaboriosam.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Verile', 'vlabbeu', '$2a$04$pgAd1jOrMjekhqEqHgJAwOoMYBr1FHtMWIbbeIJCH0FRJ.6CKBH.S', 'volijveu@newsvine.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Masha', 'msolowayv', '$2a$04$Up1Bi6DB5ikhIIPVDajkJ.tYUaROx/pj4.phBSrXt8jLNAH2aTYWy', 'mmcorkillv@a8.net', 'https://robohash.org/quisquamquaeratminus.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Athene', 'aallsupw', '$2a$04$F8pQhObkbVm1UQkpd6QZjebtHdMhxL5d8EpnhK6JocWfxP4CnR6ES', 'astockoww@about.com', 'https://robohash.org/quispossimustenetur.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Alic', 'aguinanex', '$2a$04$csiz99L/1AWSFMEIZPwTWOSD73WFEf.iqJSH1yqHzORmJ.svsNiAq', 'aschwartzx@seesaa.net', null, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Hartley', 'hpirozziy', '$2a$04$aQ1F5WFAOjCcF0AxvktaLukRa1Q4LpqCt8rLfsoIKUzFCBveZ/oGC', 'hrosendally@shareasale.com', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Paulie', 'psummerscalesz', '$2a$04$GKbn0ml0.L7v5hUZJFTIGueVpOJN5WyrE/Gz5CtUmNu37UaD.Hhpi', 'pdymentz@jiathis.com', null, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Judith', 'jkleinpeltz10', '$2a$04$DUt3guY06O6SFkHNg6V9SulBTy6g6rKhm7ol34ukFsgDAP630ALDC', 'jspaduzza10@geocities.jp', null, null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Eolande', 'epiercy11', '$2a$04$D/fNq5JlH7duoyhrCESPZ.kKmGIyaiOHj5YJUGx2D04cE2qXheQFa', 'etickel11@phpbb.com', 'https://robohash.org/repellendusrerumquia.jpg?size=500x500&set=set1', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Kristofor', 'kpuig12', '$2a$04$CEWjR3OXBl0.D3TRS0Bcw.uKELXQJe3wiM3C5A/ZnZP.XhhhsK3h.', 'kdegowe12@washington.edu', 'https://robohash.org/excepturiatiusto.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Griffy', 'gstapley13', '$2a$04$1c6ut.47e9u5CpkVdIAxH.8znwEr0E9DrJdnF6M6FCqERe/G9uYSe', 'glummus13@apple.com', 'https://robohash.org/maiorespossimusmolestias.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Olivie', 'omcgreary14', '$2a$04$9R2jLmatVQD3CWqptqXNCOqfAbSkzC5CBFmUE1quVNgW2v0maCJ.e', 'omynott14@oakley.com', 'https://robohash.org/etsedrerum.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Billy', 'bchisnall15', '$2a$04$niUYex5mY.FLp/kj5PrYZuh0gKQMcxXYNXVCSULMZaGS0wt/2UFp.', 'bkrelle15@google.it', 'https://robohash.org/distinctioearumsoluta.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Clyve', 'cable16', '$2a$04$BOZK3uUcukJP/P4gYVJHgelZmhTmCiQ1/rGVhgVxrTwu0PDf4ZODu', 'crashleigh16@hao123.com', 'https://robohash.org/quoetnon.jpg?size=500x500&set=set1', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Carolus', 'chourigan17', '$2a$04$h1HJGvXc30L/JMfLcXq2pevHv3c1SPQLvUDlmyLCtQPWymjIWwji.', 'ctopes17@blog.com', 'https://robohash.org/perspiciatisatqueut.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Neron', 'nsharp18', '$2a$04$YjW2e.l9lW.p15yj/TQ1IuIEwa.F8dQ5fQPFejxKRjPE/v8u4RO.e', 'nnovkovic18@answers.com', null, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Alex', 'afieldsend19', '$2a$04$xEG.EN2GJw1Pqn/p8MPxt.n8hksyCc7O9auYNzrWQBISgos7cQEPu', 'apetracco19@freewebs.com', null, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Diandra', 'dfiles1a', '$2a$04$dvctBfDfbGXHpTconBfHDuiu4an7LrAerCQmptmxT.hrNH5HelOgu', 'dhakey1a@home.pl', 'https://robohash.org/quisquamomnisaut.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Fielding', 'flangshaw1b', '$2a$04$Xc5jrxTH3leNN9MIVxGvf.9FSo7iH30p1xVMMIxd5YQOdY52t6bgm', 'fabrami1b@google.com.hk', 'https://robohash.org/consequunturcumqueillum.jpg?size=500x500&set=set1', null, TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Glennie', 'ggert1c', '$2a$04$m2R0kBTlpMxWNXdDmijFv.cEKV49p5SkFpuYPs66OU9q7SBAWuZz2', 'gmailes1c@bloglovin.com', 'https://robohash.org/eosetmolestiae.jpg?size=500x500&set=set1', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', TRUE);
insert into users (name, username, password, email, avatar_url, bio, verified) values ('Jorge', 'jsalliss1d', '$2a$04$6cbG.CEmS7bkrljYTnJ60e/Db8qnDJNVd.Y1z6UIg1oqXCXNFfx/q', 'jfranc1d@noaa.gov', null, null, TRUE);
